/*
 * Copyright 2026 DATA @ UHN. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Template for a client-side consumer of an extension point, generated by
// create_extension_point.py. It loads every extension registered on the point (in
// iap:defaultOrder order) and renders each one's resolved component in a grid.
//
// This is a starting point: shape the layout/props to your extension point's needs. The
// @iap/<module> import works from any module, wherever you place this file.

import { useEffect, useState, type ComponentType } from "react";

import { Grid } from "@mui/material";

import { loadExtensions } from "@iap/ui-extension/uiextension/extensionManager";

export default function _____DEFAULT_FUNCTION_NAME_____() {
  const [ components, setComponents ] = useState<ComponentType[]>([]);

  useEffect(() => {
    loadExtensions("_____EXTENSION_POINT_NAME_____")
      .then(extensions => setComponents(
        extensions.slice()
          .sort((a, b) => Number(a["iap:defaultOrder"]) - Number(b["iap:defaultOrder"]))
          .map(extension => extension["iap:extensionRender"] as ComponentType)
      ))
      .catch(err => console.error("Failed to load the _____EXTENSION_POINT_NAME_____ extensions", err));
  }, []);

  return (
    <Grid container spacing={3}>
      {
        components.map((Component, index) => (
          <Grid key={index}><Component /></Grid>
        ))
      }
    </Grid>
  );
}
